---
title: "First Knit"
author: "Deztinee Saldana"
date: "`r Sys.Date()`"
output:
  word_document:
    toc: true
    toc_depth: '5'
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
  pdf_document:
    toc: true
    toc_depth: '5'
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended Palmdale Academy Charter School. I graduated in 2025. Math class was easiest for me. I have always had some type of skill in math. My best subject was in math. The highest level math I took was AP Calculus AB. 

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I have a windows dell computer. I got this computer around 2 years ago. I would rate myself a 7 because I have barely started to use this computer. I used my chromebook throughout all my years of high school. I know how to use the computer and most of its functions. The internet connection I have is high speed. My parents have provided me access to their wifi.    
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I prefer to be called Deztinee by my classmates and instructors. I feel that it is important to keep formality in a classroom setting. My buddys call me Dez. I don't want to be called anything else by my classmates.    
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
I want to achieve success in life. I want the ability to have a house and live comfortably. The college subject that is of the greatest interest to me is math. This is because it is my major and it is required to become and actuary. I am trying to get an associates degree in mathematics for community college. I also want to transfer to a school that offers a bachelors degree in Actuarial science in the future.

   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
I have not gone to any foreign countries. I would like to go to Mexico,Italy,France, and Britain. I have never been in the military. If I got drafted, I would choose the marines because my great aunt choose that one.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
I am taking Math 116. I need it to transfer to the university I want to go to. My professor has told me that Math 115 only satisfies a general education requirement and that Math 116 counts as taking statistics in many transfer institutions. I feel like that makes sense why it is on my transfer requirements. I am planning to get an A by working hard, but I know that I have to at least pass. My plan is to get all the credits I need to transfer to a four-year university. 
   
 






  




